name: use reuse workflow with output
on:
  push:
    branches:
      - main
      - master
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Test code
        id: test-hit
        run: npm run test
      - name: Upload test report
        if: failure() && steps.test-hit.outcome == 'failure'
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: test.json
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Build website
        id: build-website
        run: npm run build
      - name: Clean Windows metadata files
        run: find dist -name '*:Zone.Identifier' -delete
      - name: Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: dist-files
          path: dist
  deploy:
    needs: build
    uses: ./.github/workflows/reusable.yml

  show_deploy_output:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Show deploy output
        run: |
          echo "deploy result is ${{ needs.deploy.outputs.deploy-info-result }}"
          # echo "from job result is ${{ needs.deploy.jobs.deploy.outputs.my-result }}"
  report:
    needs: [lint, test, build, deploy]
    runs-on: ubuntu-latest
    if: failure()
    steps:
      - name: Show report
        run: |
          echo "something wrong happened"
          echo "{{ toJSON(github) }}""